Allow image preview
irontec/ivoz-ui pull request #117
Opened 2024-06-18 09:55 UTC by rbatistadev

2024-06-18 10:39 UTC, mmadariaga requested changes

2024-06-18 10:39 UTC, mmadariaga commented on library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx
> +  const [imageSrc, setImageSrc] = useState('' as string | null);
```suggestion
  const [imageSrc, setImageSrc] = useState<string | null>(null);
```

2024-06-18 10:39 UTC, mmadariaga commented on library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx
> +    }
```suggestion
     setImageSrc(null);

      if (fileValue.file) {
        const reader = new FileReader();
        reader.onloadend = () => {
            setImageSrc(reader.result as string);
        };
        reader.readAsDataURL(fileValue.file);
        
        return;
      }

       apiDownload({
          path: downloadPath as string,
          params: {},
          successCallback: async (data: Record<string, any> | Array<Record<string, any>> | Blob) => {
            setImageSrc(URL.createObjectURL(data as Blob))
          },
       });

```
Would be easier to read / understand

2024-06-18 10:39 UTC, mmadariaga commented on library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx
> +                ? (<StyledImagePreview src={imageSrc} />)
Are we losing download feature?

2024-06-18 10:42 UTC, rbatistadev commented on library/src/services/form/Field/FileUploader/Variant/ImageFileUploader.tsx
> +                ? (<StyledImagePreview src={imageSrc} />)
yep, I'll correct!

2024-06-19 09:42 UTC, mmadariaga commented on library/package.json
>    "version": "1.3.15",
```suggestion
  "version": "1.3.16",
```

2024-06-19 09:48 UTC, mmadariaga approved these changes

2024-06-19 09:51 UTC, merged