Added collapse menu feature
irontec/ivoz-ui pull request #16
Opened 2022-09-28 14:58 UTC by fmendozzac

2022-09-28 16:24 UTC, mmadariaga requested changes

2022-09-28 16:24 UTC, mmadariaga commented on src/components/layout/Breadcrumbs/Breadcrumbs.tsx
> +          <>{homeIcon}</>
Unnecessary fragment

2022-09-28 16:24 UTC, mmadariaga commented on src/components/layout/Menu/MenuBlock.styles.tsx
> +// import { useHistory, useLocation } from 'react-router-dom';
Remove comments

2022-09-29 07:03 UTC, fmendozzac commented on src/components/layout/Menu/MenuBlock.styles.tsx
> +// import { useHistory, useLocation } from 'react-router-dom';
Done

2022-09-29 07:05 UTC, mmadariaga approved these changes

2022-09-29 07:27 UTC, merged